- .travis.yml
> why was matrix in there?

- docs/changelog.rst
- examples/plot_chord.py
- examples/plot_voronoi.py
- msmexplorer/plots/__init__.py
- msmexplorer/plots/chord.py
- msmexplorer/plots/cluster.py
- msmexplorer/tests/test_chord_plot.py
- msmexplorer/tests/test_cluster_plot.py
- msmexplorer/tests/test_hist_plot.py
- msmexplorer/tests/test_msm_plot.py
- msmexplorer/tests/test_tpt_plot.py
Adding chord diagrams for visualizing adjacency matrices (e.g. mutal information). Still not the prettiest, but at least it works. Another option is to try this with bokeh (https://www.continuum.io/blog/developer-blog/drawing-brain-bokeh)
> [WIP] Chord diagrams

- msmexplorer/plots/chord.py
- msmexplorer/plots/cluster.py
- msmexplorer/plots/msm.py
- msmexplorer/plots/tpt.py
> fix docstrings

- docs/api.rst
- docs/changelog.rst
- examples/plot_trace.py
- msmexplorer/plots/__init__.py
- msmexplorer/plots/timeseries.py
- msmexplorer/tests/test_timeseries_plot.py
- msmexplorer/utils.py
Adding time-series trace plots. Inspired by [KarlTDebiec/MolDynPlot](https://github.com/KarlTDebiec/MolDynPlot).
> Trace Plots

- README.md
- devtools/conda-recipe/meta.yaml
- docs/api.rst
- docs/conf.py
- docs/index.rst
- docs/installing.rst
- docs/notebooks/Fs-Peptide.rst
- docs/notebooks/index.rst
- docs/requirements.txt
- docs/sphinxext/embed.tpl
- docs/sphinxext/notebook_sphinxext.py
- notebooks/Fs-Peptide-Example.ipynb
> Doc improvements

- msmexplorer/plots/cluster.py
> implement gh-10

- docs/.gitignore
- msmexplorer/plots/cluster.py
- msmexplorer/plots/msm.py
- msmexplorer/plots/projection.py
- notebooks/Fs-Peptide-Example.ipynb
+ restrict timescale figure size
+ add axis labels
+ add timescale plot to notebook
> misc fixes

- msmexplorer/palettes/custom.py
Adding a few [Zapotecan-inspired](http://www.porfiriogutierrez.com/pages/natural_dyes.html) colors:
> add more colors

- devtools/conda-recipe/meta.yaml
- devtools/travis-ci/update_versions_json.py
- setup.py
> release v0.1.0

- .travis.yml
- README.md
- appveyor.yml
- devtools/conda-recipe-win/bld.bat
- devtools/conda-recipe-win/meta.yaml
> add Appveyor tests

- docs/installing.rst
- examples/plot_chord.py
- examples/plot_free_energy_1d.py
- examples/plot_free_energy_2d.py
- examples/plot_histogram.py
- examples/plot_msm_network.py
- examples/plot_pop_resids.py
- examples/plot_timescales.py
- examples/plot_tpaths.py
- examples/plot_voronoi.py
- msmexplorer/palettes/__init__.py
- msmexplorer/palettes/custom.py
- msmexplorer/plots/cluster.py
- msmexplorer/plots/msm.py
- msmexplorer/plots/projection.py
- msmexplorer/plots/timeseries.py
- msmexplorer/plots/tpt.py
- msmexplorer/utils.py
- notebooks/Fs-Peptide-Example.ipynb
add random_state, explicitly list colors, etc.
> Increase example reproducibility

- docs/changelog.rst
- msmexplorer/plots/cluster.py
This is in the same vein as #54 
- ~~Example added~~
- ~~Tests added~~
> Cluster plot changes

- .travis.yml
> Only build docs on success

- docs/changelog.rst
- examples/plot_free_energy_1d.py
- examples/plot_free_energy_2d.py
- examples/plot_msm_network.py
- examples/plot_pop_resids.py
- examples/plot_timescales.py
- examples/plot_tpaths.py
- msmexplorer/plots/msm.py
- msmexplorer/plots/projection.py
- msmexplorer/plots/tpt.py
- msmexplorer/utils.py
- notebooks/Fs-Peptide-Example.ipynb
Improve network plots, in order to add node-specific colors and sizes.
> fix up network plots

- msmexplorer/plots/__init__.py
- msmexplorer/plots/msm.py
- msmexplorer/plots/projection.py
- msmexplorer/plots/timeseries.py
re: https://github.com/msmexplorer/msmexplorer/issues/53
> force seaborn

- examples/plot_msm_network.py
- msmexplorer/plots/msm.py
- msmexplorer/plots/tpt.py
- notebooks/Fs-Peptide-Example.ipynb
> make msm pop default node size

- docs/changelog.rst
- examples/plot_free_energy_2d.py
- msmexplorer/plots/projection.py
I've seen [the colorbar issue](https://github.com/msmexplorer/msmexplorer/issues/72) and this is something that I also wanted so I've updated the function to accept color bar plotting.
- [x ] Example added
- Don't really know how to write a unit test to check if a color bar has been created, sorry.
- [ x] Docs added
- [x ] Changelog updated
> Add colorbar option to plot_free_energy

- docs/changelog.rst
- msmexplorer/plots/projection.py
The one dim free energy plot would add a shading even if its not wanted.
> minor free energy fix

- .travis.yml
- devtools/conda-recipe/meta.yaml
QT_QPA_PLATFORM="offscreen" fixes a random QT error that appeared.
re: #78
> fix travis

- msmexplorer/plots/projection.py
> Use American English

- msmexplorer/plots/projection.py
- msmexplorer/plots/timeseries.py
Removed the sns.set_style because it keeps overwriting user's style preference.
> remove style settings

- devtools/conda-recipe-win/meta.yaml
Seems to be some [weird clashing](https://ci.appveyor.com/project/cxhernandez/msmexplorer/build/1.0.238/job/44wtx41m4p4tmh2u#L152) with conda requirements in Win.
> Fix Conda Issues on Appveyor

- docs/changelog.rst
- notebooks/Fs-Peptide-Example.ipynb
Also, added some other explanatory bits across the notebook that I think can be useful.
Just added another step in the Fs-Peptide-Notebook.
> Add implied timescales plot to example notebook

- docs/changelog.rst
- examples/plot_decomp_grid.py
- msmexplorer/plots/projection.py
- msmexplorer/tests/test_projection_plot.py
A plot for displaying eigenfunctions of different decomposition objects.
> Add Decomposition Projection
